package com.crazydrt.pojo;
// Generated Feb 28, 2016 1:32:12 AM by Hibernate Tools 4.3.1

/**
 * Books generated by hbm2java
 */
public class Books {

    private String isbn;
    private String title;
    private String authors;
    private Float price;

    public Books() {
    }

    public Books(String isbn) {
        this.isbn = isbn;
    }

    public String getIsbn() {
        return this.isbn;
    }

    public void setIsbn(String isbn) {
        this.isbn = isbn;
    }

    public String getTitle() {
        return this.title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getAuthors() {
        return this.authors;
    }

    public void setAuthors(String authors) {
        this.authors = authors;
    }

    public Float getPrice() {
        return this.price;
    }

    public void setPrice(Float price) {
        this.price = price;
    }

}
